FROM alpine:latest

RUN apk add --no-cache curl caddy

# Install Tailscale
RUN curl -fsSL https://tailscale.com/install.sh | sh

COPY Caddyfile /etc/caddy/Caddyfile
COPY entrypoint.sh /entrypoint.sh

# Tailscale state volume
VOLUME /var/lib/tailscale

EXPOSE 4000

CMD ["/entrypoint.sh"]
