export const WORDS = [
  "autumn", "bridge", "candle", "dragon", "eagle", "forest", "garden",
  "harbor", "island", "jewel", "knight", "lantern", "mountain", "noble",
  "ocean", "palace", "quartz", "river", "silver", "temple", "umbrella",
  "valley", "whisper", "anchor", "blossom", "crystal", "desert", "ember",
  "feather", "glacier", "horizon", "iris", "journey", "kingdom", "lunar",
  "meadow", "nebula", "oracle", "pearl", "riddle", "sapphire", "thunder",
  "violet", "willow", "zenith", "amber", "breeze", "copper", "dawn",
  "echo", "frost", "gravel", "hollow", "ivory", "jade", "koi",
  "lily", "maple", "night", "onyx", "pebble", "raven", "solar",
  "topaz", "vapor", "winter", "yonder", "zephyr", "aster", "briar",
  "cedar", "dusk", "elm", "flint", "grove", "hazel", "iris",
  "juniper", "kelp", "laurel", "mist", "nova", "olive", "pine",
  "quartz", "reed", "spruce", "thistle", "umber", "vine", "wheat",
  "yarrow", "acorn", "birch", "coral", "drift", "emerald", "fern",
  "garnet", "hemlock", "indigo", "jasper", "kestrel", "limestone",
  "marble", "nectar", "opal", "pumice", "ruby", "slate", "turquoise",
  "elm", "falcon", "gull", "hawk", "ibis", "jay", "koala",
  "lark", "moth", "newt", "owl", "panda", "quail", "robin",
  "swan", "toad", "viper", "wren", "alpaca", "badger", "crane",
  "deer", "eel", "fox", "goat", "hare", "ibex", "jackal",
  "koi", "lemur", "moose", "newt", "otter", "puma", "quokka",
  "ram", "seal", "tiger", "urchin", "vole", "walrus", "yak",
  "zebra", "aster", "comet", "diadem", "eclipse", "flame", "glow",
  "halo", "flare", "light", "nova", "orbit", "plasma", "quasar",
  "radiant", "shimmer", "twinkle", "aurora", "blaze", "cosmos", "flare",
  "glimmer", "helium", "infinity", "jupiter", "mars", "mercury",
  "neptune", "photon", "saturn", "uranus", "venus", "warp", "xenon",
  "yield", "zeta", "alpha", "beta", "gamma", "delta", "epsilon",
  "theta", "kappa", "lambda", "omega", "phi", "psi", "sigma"
].filter(w => w.length >= 3);
